// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpviuxlpyrsovhkxryml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwdml1eGxweXJzb3Zoa3hyeW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODA0NjYsImV4cCI6MjA2MTU1NjQ2Nn0.ZYxf4oGTvU-emC4ilU28kKSe6JkSQY_T8qeQ0p529B0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);